name: continuous integration

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  os_x:
    runs-on: macos-11
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh os_x
